// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIiQuJu6pjakC5wuQ2-loK6Hqum8VkVnU',
    appId: '1:681752742995:web:6afc02729b54738bc48aa6',
    messagingSenderId: '681752742995',
    projectId: 'first-intership-project',
    authDomain: 'first-intership-project.firebaseapp.com',
    storageBucket: 'first-intership-project.appspot.com',
    measurementId: 'G-TVDL4ZY0T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfEf30jKQtv0FiaQH_thevlJGFsYE91c',
    appId: '1:681752742995:android:73c9490e1a2ce235c48aa6',
    messagingSenderId: '681752742995',
    projectId: 'first-intership-project',
    storageBucket: 'first-intership-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-UibwfOcDwxMT4ECawZaSW4C68NhsdU',
    appId: '1:681752742995:ios:86cbf0bd230421a9c48aa6',
    messagingSenderId: '681752742995',
    projectId: 'first-intership-project',
    storageBucket: 'first-intership-project.appspot.com',
    iosBundleId: 'com.example.firstProjectProfileCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw-UibwfOcDwxMT4ECawZaSW4C68NhsdU',
    appId: '1:681752742995:ios:86cbf0bd230421a9c48aa6',
    messagingSenderId: '681752742995',
    projectId: 'first-intership-project',
    storageBucket: 'first-intership-project.appspot.com',
    iosBundleId: 'com.example.firstProjectProfileCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIiQuJu6pjakC5wuQ2-loK6Hqum8VkVnU',
    appId: '1:681752742995:web:89ee88a714c68eb1c48aa6',
    messagingSenderId: '681752742995',
    projectId: 'first-intership-project',
    authDomain: 'first-intership-project.firebaseapp.com',
    storageBucket: 'first-intership-project.appspot.com',
    measurementId: 'G-VWTXVDRQ9K',
  );
}
